### ISSUE TITLE
Soup?

### ISSUE THREAD

**Issue by NoodlesNZ** [iuscommunity-pkg/php56u#10]
https://github.com/iuscommunity-pkg/php56u/blob/master/SPECS/php56u.spec#L588
Is this meant to be config(%{real_name}-soap) ?

**Comment by cgtx** [comment]
We just really like soup.  Here, have some.

![soup](http://lindawagner.net/blog/wp-content/uploads/2013/11/MG_7816.jpg)

**Comment by cgtx** [comment]
Just kidding, of course it's a typo.  Thanks for catching that!  Fixed with f9b787a33fe3c3be747f7e96d028b22e3555bfb5.

**Comment by cgtx** [comment]
PHP 5.6.5 is scheduled to be released upstream on Thursday, so we'll get this fix packaged at the same time.
