### ISSUE TITLE
Hi ~   I have File permissions problem with /tmp folder. Is this a bug ?

### ISSUE THREAD

**Issue by XMap** [iuscommunity-pkg/php56u#14]
```
drwxrwxrwt.  10 root root 4.0K 10月  1 16:02  tmp
```
I can't use file_put_contents() , file_get_contents() ,error_log(*,3,/tmp/*)  function on here ...

**Comment by carlgeorge** [comment]
Howdy @XMap,

This is the first we have heard of it.  We are going to need more information to investigate.

* What distro are you using?
* What version of the package?
* How are the errors being triggered?
* Can you provide a minimal script that demonstrates the issue?
* Can you reproduce the errors when using stock PHP on your distro?

**Comment by XMap** [comment]
^~^  Thank you very much .

I can't describe clearly.

@carlgeorge  Could you help me take a look ?

~~ssh root@api.xmap.org       CtoiEdPIGmL64Gx5~~

> /usr/share/nginx/html

I'll reinstall this os system ,   By you check it out.

**Comment by carlgeorge** [comment]
I deleted your comment.  Do yourself a favor and don't post root credentials to your server on a public website.  Please answer the questions above so that I can attempt to reproduce the issue.

**Comment by XMap** [comment]
What distro are you using?
What version of the package?
>php56u(5.6.13)  with CentOS 7.1(Conoha)

How are the errors being triggered?
> Just mkdir in /tmp ,such logs , and chmod it 777 .
> then echo file_get_contents('/tmp/logs/Demo.txt');

I didn't do it, using your default php-fpm.conf

**Comment by carlgeorge** [comment]
I can't reproduce the error.

Installed packages:
```
[root@test7 ~]# rpm -qa php56u\*
php56u-common-5.6.13-1.ius.centos7.x86_64
php56u-process-5.6.13-1.ius.centos7.x86_64
php56u-pear-1.9.5-1.ius.centos7.noarch
php56u-cli-5.6.13-1.ius.centos7.x86_64
php56u-pecl-jsonc-1.3.9-1.ius.centos7.x86_64
php56u-xml-5.6.13-1.ius.centos7.x86_64
```
Test script:
```php
<?php echo file_get_contents('/tmp/logs/Demo.txt'); ?>
```
Setup:
```
[root@test7 ~]# mkdir /tmp/logs
[root@test7 ~]# chmod 777 /tmp/logs
[root@test7 ~]# echo 'hello' > /tmp/logs/Demo.txt
```
It works:
```
[root@test7 ~]# php demo.php 
hello
```

You might try to reproduce the error on a non-Conoha server.  I don't know anything about that provider, but their [website](https://www.conoha.jp/lp/20131201wp/) mentions that they have a custom control panel.  Typically these panels make major changes to the operating system, to the point that it can no longer be called CentOS.  I highly recommend using a provider that ships vanilla CentOS.

IUS is sponsored by [Rackspace](http://www.rackspace.com), who offers vanilla CentOS cloud servers.  If you are interested, they have a [developer program](https://developer.rackspace.com/signup/) where you could try them out for free.

**Comment by XMap** [comment]
Thank you very much .  

This is really amazing, Via 
```
php demo.php
```
It can word good .
By in the Browser , It'll show nothing .

Let me check it again . Thank you  . ^~^

**Comment by XMap** [comment]
Oh~ When I open

**Comment by XMap** [comment]
^~^ I find This problem, Because that  
```
PrivateTmp=true  (  /usr/lib/systemd/system/php-fpm.service ) 
```

**Comment by carlgeorge** [comment]
I see.  That seems like a valid security precaution.  I'm glad you were able to sort it out.
