### ISSUE TITLE
10-php.conf file deleted with latest update

### ISSUE THREAD

**Issue by geoiii** [iuscommunity-pkg/php56u#15]
If this is the wrong place to report issues like this please point me to the correct one.

It appears in the most recent update that when doing a yum update 10-php.conf file is removed. 
This file contained these lines:

```
\#
\# PHP is an HTML-embedded scripting language which attempts to make it
\# easy for developers to write dynamically generated webpages.
\#
<IfModule prefork.c>
  LoadModule php5_module modules/libphp5.so
</IfModule>

<IfModule !prefork.c>
  LoadModule php5_module modules/libphp5-zts.so
</IfModule>

```

I see that these lines were added to php.conf in a eariler update - and on my severs that php.conf did get correctly installed earlier in the month as php.conf.rpmnew. 

I also saw this reported by another person here:

https://serverfault.com/questions/758606/10-php-conf-deleted-apache-conf

**Comment by carlwgeorge** [comment]
Howdy @geoiii,

Yes, this is the correct place to report bugs for this package.

On Fedora and EL7, httpd loads modules from `/etc/httpd/conf.modules.d`, and then other configuration from `/etc/httpd/conf.d`.  When we created this package, we did not properly implement conditionals around that section of the spec file, which resulted in `/etc/httpd/conf.d/php.conf` and `/etc/httpd/conf.d/10-php.conf` both existing on EL6.  As part of the `5.6.18-1.ius` update, we [corrected this oversight](https://github.com/iuscommunity-pkg/php56u/commit/588e18) by concatenating those two source files together so we just have a single `/etc/httpd/conf.d/php.conf` file, which is how stock PHP on EL6 does things.

Once you merge `php.conf.rpmnew` into your existing configuration file, everything should work fine.  If you modified `10-php.conf`, you might have a `10-php.conf.rpmsave` file to merge in as well.  Sorry for the inconvenience.
