### ISSUE TITLE
php-fpm init script should pass --daemonize argument

### ISSUE THREAD

**Issue by SJrX** [iuscommunity-pkg/php56u#17]
For no good reason, our php-fpm.conf was set to daemonize=no. This didn't matter because our previous php-fpm scripts, and when I tried the webtatic rpms, both forced --daemonize when it called php-fpm in the init script. Currently the ius packages do not, and rely on the configuration being set to yes, if it is no the init script hangs. This will cause deployers like ansible to hang, and presumably would stop the system from booting. 

I have already changed our script, and agree it is a stupid use case. But I think that the init script should be fixed to force this.

**Comment by carlwgeorge** [comment]
Howdy @SJrX,

I totally agree.  I can see that the systemd service file takes the same approach (it doesn't want the process to fork, so it passes `--nodaemonize`).  I'll updated the init script to include the `--daemonize` flag.
