### ISSUE TITLE
always_populate_raw_post_data default value is incorrect

### ISSUE THREAD

**Issue by kustodian** [iuscommunity-pkg/php56u#20]
This is a follow up to #19, and since that one was closed without the real resolution, I'm opening a new on.

The issue is that the commented setting in `php.ini` is incorrect. It is set to:
```
;always_populate_raw_post_data = -1
```
Which suggests that the default value is `-1`, but it's not, the actual default is `0`. Could you please change the commented value in `php.ini` to `0`, so it's displaying the correct value, since currently it is misleading.

If you ask me it's stupid how PHP implemented this warning, because it's reporting the error when the variable is populated, not used, but the commented value in `php.ini` should be correct.

**Comment by carlwgeorge** [comment]
Don't split the conversation, keep it in the original issue.

**Comment by carlwgeorge** [comment]
Remember, you can comment on closed issues.

**Comment by kustodian** [comment]
Usually on open source projects devs tend to stop watching closed issues, so it's better to open a new one and reference the old one. I will add a comment in the old one.
