### ISSUE TITLE
php56u uwsgi plugin

### ISSUE THREAD

**Issue by 00Asgaroth00** [iuscommunity-pkg/php56u#23]
Hi,

I am trying to use the IUS php56u packages installed on centos 7.3 with EPEL's uwsgi. I see that uwsgi has a php plugin (uwsgi-plugin-php) which is dependent on the systems version of php (5.4.16).

I tried to do a standard install of php56u without the systems php previously installed, but the uwsgi-plugin-php package will not install in this case (dependant on the system's php package).

I then tried to install the system's version of php and EPEL's edition of uwsgi-plugin-php, then tried a "yum replace php --replace-with php56u", which successfully completed but removed the uwsgi-plugin-php package which depends on the system php package.

How would I go about installing php56u with EPEL's uwsgi package, or, is it possible for you to create a uwsgi-plugin-php56u package like you did for php70u (uwsgi-plugin-php70u)?

Any tips would be greatly appreciated.

**Comment by carlwgeorge** [comment]
This would require a uwsgi-plugin-php56u package.  Please create a request on our [wishlist](https://github.com/iuscommunity/wishlist).

**Comment by 00Asgaroth00** [comment]
Thanks for the update, wish created :)
