### ISSUE TITLE
CentOS7 NSS bug relation?

### ISSUE THREAD

**Issue by laupow** [iuscommunity-pkg/php56u#24]
CentOS7 released an NSS update yesterday which, after updating (and then rolling back), we noticed caused severe curl/SSL issues: https://bugs.centos.org/view.php?id=12937

I don't think these bugs are related to the IUS PHP distributions, but I can't help but wonder if there's any conflict between the kernel, NSS, and the PHP package expectations.

**Comment by b-harper** [comment]
Hey @laupow,

Thanks for taking the time to create this issue.  A quick look over that bug, it would seem this is an issue with the web server interaction with NSS and not PHP.   Let me look more into this more and I will update this issue when more information is available.

**Comment by b-harper** [comment]
@laupow, are you using stock httpd or IUS httpd24u?

We are hearing reports that NSS is breaking stock httpd in general.  If you are using stock httpd, then the PHP stack does not matter.

**Comment by laupow** [comment]
Stock httpd. It turns out a fix that has worked pretty well so far for us
was "as simple" as restarting httpd.

**Comment by b-harper** [comment]
From what we are hearing, restarting apache is all that is needed.  I am going to close this for now, but feel free to update if you come across additional information.
