### ISSUE TITLE
php56u packages 5.6.31 security update

### ISSUE THREAD

**Issue by cesarjorgemartinez** [iuscommunity-pkg/php56u#25]
Hi,

To secure the php, I need the new version of php packages of version 5.6.31.
Looking in the stable repository do not come those RPMS.

Regards

**Comment by b-harper** [comment]
Hey @cesarjorgemartinez,

The RPMs for php56u 5.6.31 are still in the [testing repositories][0].


[0]: https://dl.iuscommunity.org/pub/ius/testing/CentOS/7/x86_64/repoview/php56u.html

**Comment by philtech-oh** [comment]
Hi @b-harper,

Any idea on when the 5.6.31 RPMs will be available in the stable repo?

Thanks,
Phil

**Comment by b-harper** [comment]
Hey @philtech-oh,

Typically, packages stay in the testing repositories for [two weeks][0], unless there is cause to promote them ahead of schedule like for security fixes.  It can be tricky to determine how long to keep them in the testing repositories.  We want to give a reasonable amount of time for users to test, but we also want to push out the updates in a timely fashion.

We will go ahead and push the php56u 5.6.31 to the stable repositories during tonight's automation run.  If you need the packages now, please [use the testing repositories][1].


[0]: https://ius.io/Philosophy/#release-policy
[1]: https://ius.io/Usage/#using-testing-repositories
