### ISSUE TITLE
php56u-pdo-5.6.32-1 not satisfying php-sqlite3 after cleanup

### ISSUE THREAD

**Issue by amillis** [iuscommunity-pkg/php56u#26]
Was this part of the last cleanup of the spec supposed to get removed?
> %if 0%{?rhel} >= 6
> %global with_sqlite3 1
> %else
> %global with_sqlite3 0
> %endif

Without it, this later section in the spec probably isn't happening:
> %if 0%{?with_sqlite3}
> Provides: %{name}-sqlite3, %{name}-sqlite3%{?_isa}
> Provides: %{real_name}-sqlite3, %{real_name}-sqlite3%{?_isa}
> %endif # with_sqlite3

5.6.31-1 satisfied the php-sqlite3 dependency:
> $ rpm -q --whatprovides php-sqlite3
> php56u-pdo-5.6.31-1.ius.centos7.x86_64

Running yum update on a php56u-5.6.31 system that already has dependent packages that php-sqlite3 was satisfied is causing yum to try to pull in the stock php54 (causing conflicts) when it tried to do the 5.6.32 update.

> $ yum deplist php-symfony-http-kernel
>   ...
>   dependency: php-sqlite3
>    provider: php71u-pdo.x86_64 7.1.11-1.ius.centos7
>    provider: php70u-pdo.x86_64 7.0.25-1.ius.centos7
>    provider: php-pdo.x86_64 5.4.16-43.el7_4
>   ...

**Comment by zetarhopike** [comment]
Adding the snip below back to the spec file and rebuilding resolved the issue for us on RHEL7.
```
%if 0%{?rhel} >= 6
%global with_sqlite3 1
%else
%global with_sqlite3 0
%endif
```

**Comment by b-harper** [comment]
Hey @amillis and @zetarhopike,

Thanks for bringing this issue to our attention and pin pointing the root cause.  I'll get started at at addressing the issue and new packages built.

**Comment by b-harper** [comment]
Update packages have been built and will hit the testing repositories during tonight's automation run.  

@amillis to answer you question, yes that bit of code was removed intentional, just more code needed to be removed at the same time.

**Comment by amillis** [comment]
Looks good!  Much neater this way.  Thanks for the quick turnaround.

**Comment by b-harper** [comment]
After tonight's automation run, the updated packages will be pushed to the stable repositories.
