### ISSUE TITLE
php56u-pecl-krb5 broken dependency to libkadm5clnt_mit.so.8 on CentOS 7.5

### ISSUE THREAD

**Issue by joernott** [iuscommunity-pkg/php56u#27]
php${PHP_VERSION}-pecl-krb5 requires libkadm5clnt_mit.so.8. The only available package libkadm5-1.15.1-19.el7.x86_64 installs libkadm5clnt_mit.so.11.0 resulting in a broken dependency.

**Comment by carlwgeorge** [comment]
Thanks for the heads up on this.  It also affects the EPEL php-pecl-krb5 package ([rhbz#1567515](https://bugzilla.redhat.com/show_bug.cgi?id=1567515)).  I'm rebuilding this package now to link against the new library.

**Comment by carlwgeorge** [comment]
Can you reopen this in the right repo?

https://github.com/iuscommunity-pkg/php56u-pecl-krb5/issues
