### ISSUE TITLE
 php56u-pecl-amqp-1.9.3-1 dependency problem withlibrabbitmq.so on CentOS 7.5

### ISSUE THREAD

**Issue by joernott** [iuscommunity-pkg/php56u#28]
CentOS 7.5/base provides librabbitmq-0.8.0-2 which updates librabbitmq-0.5.2-1 from epel. As librabbitmq-0.5.2-1 is required by  php56u-pecl-amqp-1.9.3-1, yum install runs into problems on up-to-date CentOS 7.5 or when updating from CentOS 7.4

**Comment by carlwgeorge** [comment]
Can you reopen this in the right repos?

https://github.com/iuscommunity-pkg/php56u-pecl-amqp/issues
https://github.com/iuscommunity-pkg/php70u-pecl-amqp/issues
https://github.com/iuscommunity-pkg/php71u-pecl-amqp/issues
